### ISSUE TITLE
SearchGrid implementation missing

### ISSUE THREAD

**Issue by githendrik** [php-pike/pike#1]
Hi guys,

first off: Great project you have. I've been loving it so far.

One thing I've come across (but was unable to implement myself) is that the searchGrid option seems to be not yet implemented. I can search for entries by using the filter toolbar, however using the pop-up via searchGrid option will always return all entries, without  the filter applied. I'm suspecting the Datasource object does not yet take the parameters searchField / searchString / searchOper into consideration, only the filters option.

It would be great if this feature could be implemented at some point. 

Best Regards,
Hendrik

**Comment by php-pike** [comment]
Your conclusion is correct @githendrik the server doesn't do anything yet with these parameter. As I wrote you we will implement this in the near future in PiKe after we make the library more stable. Offcourse you are free to fork and try it yourself or wait for us until we implement this feature. 

Thanks for asking and supporting us!
