### ISSUE TITLE
Using Concat in Datasource-Query breaks all filtering

### ISSUE THREAD

**Issue by githendrik** [php-pike/pike#3]
I am trying to use Pike 1.2 (53) together with some of Mysqls concat functions in a project. 
Unfortunately it seems that if a concat field is present in the query, the whole Datasource will stop responding to filters (not only the concat'ed field, but all).

Is there any chance this might be fixed in the future? I am currently trying to find a solution myself, but so far without much luck.

Best regards,
Hendrik

**Comment by pietervogelaar** [comment]
Isn't it possible to do the concatenate part in PHP code? You now the possibility that you can specifiy an anonymous function as the data key for a column? The database row is passed to it as the first argument. So there you can concatenate and return the value in the function.

**Comment by githendrik** [comment]
That was my initial idea as well. However for some reason my custom formatter is not accepted by Jqgrid.
Also, I think it would be more consistent to specify the fields to be concatenated in the select clause instead of writing and applying custom formatters for every occasion. It would also be a pain to have to hide all source fields of the concat after formatting.

EDIT: I had success formatting a field so that it represents a concatenation of 2 other fields. However, there are 3 shortcomings in this approach:

1) The formatter needs the exact positions of the fields (row object is a regular array) to be concatenated
2) The fields need to be hidden manually
3) Filtering only works for the data that is in the field by default. In my example I used zip code and city. I have hidden the zip code field and added a custom formatter to the city. The formatter then uses the index of city and concatenates it with the prepended zip code (City-Index -1 in the row array). The problem here is that filtering only works for city, not for zip code.
